services:
  collect_data:
    build:
      context: .
      dockerfile: server-collect_data/Dockerfile
    volumes:
      - ./server-collect_data:/app/server-collect_data
      - ./shared:/app/shared
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app:/app/server-collect_data
      - TZ=Asia/Seoul
    command: python server-collect_data/fetcher/main_fetch.py
    depends_on:
      - db
    restart: always
    networks:
      - trading_net

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - trading_net

volumes:
  pgdata:

networks:
  trading_net: